name: Deploy to EC2

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
            buildkitd-flags: --debug
    
      - name: Install Docker Compose
        run: |
              sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
              docker-compose --version

      - name: Create required directories
        run: |
          mkdir -p definitions/AgentDef definitions/TaskDef
          mkdir -p src/ant_ai
          mkdir -p logs notebooks
          touch definitions/AgentDef/.gitkeep definitions/TaskDef/.gitkeep

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and save Docker image
        run: |
          # Show directory structure
          echo "Current directory structure:"
          ls -la
          echo "\nContents of src/ant_ai:"
          ls -la src/ant_ai
          echo "\nContents of definitions:"
          ls -la definitions
          
          # Build the image
          DOCKER_BUILDKIT=1 docker-compose build --no-cache
          
          # Save the image
          docker save ant-ai-vercel_ant_ai:latest | gzip > image.tar.gz

      - name: Deploy to EC2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.AWS_SSH_KEY }}
          EC2_HOST: ${{ secrets.AWS_EC2_HOST }}
          ENV_FILE: ${{ secrets.ENV_PROD }}
        run: |
          # Save SSH key
          echo "$SSH_PRIVATE_KEY" > ssh-key.pem
          chmod 400 ssh-key.pem
          
          # Save env file
          echo "$ENV_FILE" > .env
          
          # Create directory on EC2
          ssh -i ssh-key.pem -o StrictHostKeyChecking=no ubuntu@$EC2_HOST "mkdir -p /home/ubuntu/ant-ai"
          
          # Copy files to EC2
          scp -i ssh-key.pem -o StrictHostKeyChecking=no \
            image.tar.gz \
            docker-compose.yml \
            .env \
            ubuntu@$EC2_HOST:/home/ubuntu/ant-ai/
          
          # Deploy on EC2
          ssh -i ssh-key.pem -o StrictHostKeyChecking=no ubuntu@$EC2_HOST << 'EOF'
            cd /home/ubuntu/ant-ai
            docker-compose down || true
            docker load < image.tar.gz
            docker-compose up -d
            docker-compose ps
          EOF

      - name: Cleanup
        if: always()
        run: rm -f ssh-key.pem .env image.tar.gz 
