name: Deploy to EC2

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and save Docker image
        run: |
          docker-compose build
          docker save ant_ai:latest | gzip > image.tar.gz

      - name: Deploy to EC2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.AWS_SSH_KEY }}
          EC2_HOST: ${{ secrets.AWS_EC2_HOST }}
          ENV_FILE: ${{ secrets.ENV_PROD }}
        run: |
          # Save SSH key
          echo "$SSH_PRIVATE_KEY" > ssh-key.pem
          chmod 400 ssh-key.pem
          
          # Save env file
          echo "$ENV_FILE" > .env
          
          # Copy files to EC2
          scp -i ssh-key.pem -o StrictHostKeyChecking=no \
            image.tar.gz \
            docker-compose.yml \
            .env \
            ubuntu@$EC2_HOST:/home/ubuntu/ant-ai/
          
          # Deploy on EC2
          ssh -i ssh-key.pem -o StrictHostKeyChecking=no ubuntu@$EC2_HOST << 'EOF'
            cd /home/ubuntu/ant-ai
            docker-compose down
            docker load < image.tar.gz
            docker-compose up -d
          EOF

      - name: Cleanup
        if: always()
        run: rm -f ssh-key.pem .env image.tar.gz 
