name: Deploy to AWS EC2

on:
  workflow_dispatch:
  push:
    branches: [main, master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install required packages
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose-plugin pigz rsync
          docker-compose --version

      - name: Set up environment variables
        run: |
          echo -e "${{ secrets.ENV_PROD }}" >> .env
          echo "IMAGE_NAME=ant-ai-vercel-ant_ai" >> .env
          echo "CONTAINER_NAME=ant-ai" >> .env

      - name: Build Docker image
        run: |
          echo "Building Docker image..."
          DOCKER_BUILDKIT=1 docker-compose build --no-cache
          echo "Image details:"
          docker images ant-ai-vercel-ant_ai

      - name: Save and compress Docker image
        run: |
          echo "Saving and compressing image..."
          docker save ant-ai-vercel-ant_ai:latest | pigz -9 > ant-ai.tar.gz
          echo "Compressed image size:"
          ls -lh ant-ai.tar.gz

      - name: Setup SSH and directory on EC2
        run: |
          # Setup SSH key
          echo "${{ secrets.AWS_SSH_KEY }}" > ssh-key.pem
          chmod 400 ssh-key.pem

          # Prepare EC2 instance
          ssh -i ssh-key.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.AWS_EC2_HOST }} '
            # Create and set permissions for app directory
            sudo mkdir -p /home/ubuntu/ant-ai
            sudo chown -R ubuntu:ubuntu /home/ubuntu/ant-ai
            
            # Install required packages if not present
            if ! command -v pigz &> /dev/null; then
              sudo apt-get update
              sudo apt-get install -y pigz docker-compose
            fi

            # Clean up old files
            rm -rf /home/ubuntu/ant-ai/*
          '

      - name: Transfer files to EC2
        run: |
          echo "Transferring files to EC2..."
          rsync -avz --progress -e "ssh -i ssh-key.pem -o StrictHostKeyChecking=no" \
            --compress-level=9 \
            .env docker-compose.yml ant-ai.tar.gz \
            ubuntu@${{ secrets.AWS_EC2_HOST }}:/home/ubuntu/ant-ai/

      - name: Deploy application
        run: |
          ssh -i ssh-key.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.AWS_EC2_HOST }} << 'EOF'
            cd /home/ubuntu/ant-ai

            # Setup Docker permissions
            sudo usermod -aG docker ubuntu
            sudo chmod 666 /var/run/docker.sock

            echo "Stopping existing containers..."
            sudo docker-compose down --remove-orphans || true
            
            echo "Cleaning up old images..."
            sudo docker system prune -af
            sudo docker rmi ant-ai-vercel-ant_ai:latest || true

            echo "Loading new image..."
            pigz -dc ant-ai.tar.gz | sudo docker load
            
            echo "Starting application in detached mode..."
            sudo docker-compose up -d

            echo "Waiting for application to start..."
            sleep 10

            echo "Container status:"
            sudo docker-compose ps

            echo "Initial container logs:"
            sudo docker-compose logs

            echo "Cleaning up..."
            rm -f ant-ai.tar.gz
          EOF

      - name: Verify deployment
        run: |
          echo "Checking application status..."
          curl -sSf http://${{ secrets.AWS_EC2_HOST }}:8501 || echo "Application not responding on port 8501"

      - name: Cleanup
        if: always()
        run: |
          echo "Cleaning up local resources..."
          rm -f ssh-key.pem .env ant-ai.tar.gz
          docker-compose down --remove-orphans
          docker system prune -af 
