name: Deploy to AWS EC2

on:
  workflow_dispatch:
  push:
    branches: [main, master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Set up environment variables
        run: |
          echo -e "${{ secrets.ENV_PROD }}" >> .env
          echo "IMAGE_NAME=ant-ai-vercel-ant_ai" >> .env
          echo "CONTAINER_NAME=ant-ai" >> .env

      - name: Build Docker image with Docker Compose
        run: |
          set -e
          docker-compose build --no-cache
          docker images

      - name: Save and compress Docker image
        run: |
          set -e
          IMAGE_NAME="ant-ai-vercel-ant_ai"
          echo "Saving image: $IMAGE_NAME"
          docker save $IMAGE_NAME:latest | gzip > ant-ai.tar.gz
          ls -lh ant-ai.tar.gz

      - name: Copy files to EC2
        run: |
          echo "${{ secrets.AWS_SSH_KEY }}" >> ssh-key.pem
          chmod 400 ssh-key.pem

          ssh -i ssh-key.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.AWS_EC2_HOST }} '
            sudo mkdir -p /home/ubuntu/ant-ai
            sudo chown -R ubuntu:ubuntu /home/ubuntu/ant-ai
            rm -f /home/ubuntu/ant-ai/ant-ai.tar.gz
          '

          scp -i ssh-key.pem -o StrictHostKeyChecking=no .env ubuntu@${{ secrets.AWS_EC2_HOST }}:/home/ubuntu/ant-ai/.env
          scp -i ssh-key.pem -o StrictHostKeyChecking=no docker-compose.yml ubuntu@${{ secrets.AWS_EC2_HOST }}:/home/ubuntu/ant-ai/docker-compose.yml
          rsync --progress -e "ssh -i ssh-key.pem -o StrictHostKeyChecking=no" ant-ai.tar.gz ubuntu@${{ secrets.AWS_EC2_HOST }}:/home/ubuntu/ant-ai/

      - name: Deploy to EC2
        run: |
          ssh -i ssh-key.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.AWS_EC2_HOST }} << 'EOF'
            set -e
            cd /home/ubuntu/ant-ai

            sudo usermod -aG docker ubuntu
            sudo chown -R ubuntu:ubuntu /home/ubuntu/ant-ai
            sudo chmod 666 /var/run/docker.sock

            echo "Stopping existing containers..."
            sudo docker-compose down || true
            
            echo "Removing old image..."
            sudo docker rmi ant-ai-vercel-ant_ai:latest || true

            echo "Loading new image..."
            sudo gunzip -c ant-ai.tar.gz | sudo docker load
            
            echo "Starting containers..."
            sudo docker-compose up -d

            echo "Cleaning up..."
            rm -f ant-ai.tar.gz
            
            echo "Deployment complete! Container logs:"
            sudo docker-compose logs
          EOF

      - name: Cleanup local files
        run: |
          rm -f ssh-key.pem .env ant-ai.tar.gz
          docker-compose down || true
          docker rmi ant-ai-vercel-ant_ai:latest || true 
